/* eslint-disable react-hooks/exhaustive-deps -- refresh runs when identity changes; search is submitted explicitly. */
import {FormEvent,useEffect,useState}from'react';
type Product={id:string;sku:string;name:string;on_hand:number;reserved:number;available:number;reorder_threshold:number};type Stock={product_id:string;warehouse_id:string;sku:string;name:string;warehouse_code:string;on_hand:number;reserved:number;available:number};
const base='';
export function App(){const[token,setToken]=useState(localStorage.getItem('token')??'');const[role,setRole]=useState(localStorage.getItem('role')??'');const[products,setProducts]=useState<Product[]>([]);const[stock,setStock]=useState<Stock[]>([]);const[tab,setTab]=useState(location.hash.slice(1)||'catalog');const[status,setStatus]=useState('');const[q,setQ]=useState(new URLSearchParams(location.search).get('q')??'');
 const api=async(path:string,init?:RequestInit)=>{const r=await fetch(base+path,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,'idempotency-key':crypto.randomUUID(),...init?.headers}});const body=await r.json();if(!r.ok)throw new Error(body.error?.message??'Request failed');return body};
 const refresh=async()=>{if(!token)return;setStatus('Loading…');try{const[p,s]=await Promise.all([api(`/api/products?q=${encodeURIComponent(q)}`),api('/api/stock')]);setProducts(p.data);setStock(s.data);setStatus('');}catch(e){setStatus(e instanceof Error?e.message:'Unable to load');}};useEffect(()=>{void refresh()},[token]);
 const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const x=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})}).then(r=>r.json());if(!x.token)throw new Error(x.error?.message);localStorage.setItem('token',x.token);localStorage.setItem('role',x.user.role);setRole(x.user.role);setToken(x.token)}catch(e){setStatus(e instanceof Error?e.message:'Sign in failed')}};
 const navigate=(name:string)=>{location.hash=name;setTab(name)};if(!token)return <main className="login"><h1>Inventory & Orders</h1><p>Sign in to the local demonstration environment.</p><form onSubmit={login}><label>Email<input name="email" defaultValue="admin@example.com" type="email" required/></label><label>Password<input name="password" defaultValue="demo-password" type="password" required/></label><button>Sign in</button><p role="alert">{status}</p></form></main>;
 const submit=async(path:string,data:unknown)=>{setStatus('Saving…');try{await api(path,{method:'POST',body:JSON.stringify(data)});setStatus('Saved successfully');await refresh()}catch(e){setStatus(e instanceof Error?e.message:'Save failed')}};
 return <><header><div><strong>Northstar Inventory</strong><small>Demo Distribution · {role}</small></div><button onClick={()=>{localStorage.clear();setToken('')}}>Sign out</button></header><nav aria-label="Primary">{['catalog','stock','purchasing','sales','receiving','fulfillment','reports'].map(x=><button aria-current={tab===x?'page':undefined} onClick={()=>navigate(x)} key={x}>{x}</button>)}</nav><main><p className="status" role="status" aria-live="polite">{status}</p>
 {tab==='catalog'&&<section><h1>Catalog</h1><form className="search" onSubmit={e=>{e.preventDefault();history.replaceState({},'',`?q=${encodeURIComponent(q)}#catalog`);void refresh()}}><label>Search products<input value={q} onChange={e=>setQ(e.target.value)}/></label><button>Search</button></form><Data rows={products}/>{['admin','catalog'].includes(role)&&<QuickProduct onSave={x=>submit('/api/products',x)}/>}</section>}
 {tab==='stock'&&<section><h1>Warehouse stock</h1><Data rows={stock}/>{role==='admin'&&<Adjust rows={stock} onSave={x=>submit('/api/stock/adjust',x)}/>}</section>}
 {tab==='purchasing'&&<Workflow title="Purchase orders" help="Create a multi-line draft, then submit it through the named command endpoint." fields={['supplierId','warehouseId','productId','quantity','unitCostCents']} onSave={v=>submit('/api/purchase-orders',{supplierId:v.supplierId,warehouseId:v.warehouseId,lines:[{productId:v.productId,quantity:Number(v.quantity),unitCostCents:Number(v.unitCostCents)}]})}/>} 
 {tab==='sales'&&<Workflow title="Sales orders" help="Creating an order atomically reserves currently available stock." fields={['warehouseId','customerName','productId','quantity','unitPriceCents']} onSave={v=>submit('/api/sales-orders',{warehouseId:v.warehouseId,customerName:v.customerName,lines:[{productId:v.productId,quantity:Number(v.quantity),unitPriceCents:Number(v.unitPriceCents)}]})}/>} 
 {tab==='receiving'&&<Workflow title="Receiving" help="Receive ordered units partially. Repeated idempotency keys cannot double-receive." fields={['purchaseOrderId','warehouseId','productId','quantity']} onSave={v=>submit(`/api/purchase-orders/${v.purchaseOrderId}/receive`,{warehouseId:v.warehouseId,productId:v.productId,quantity:Number(v.quantity)})}/>} 
 {tab==='fulfillment'&&<Workflow title="Fulfillment" help="Ship reserved units partially; on-hand and reserved decrease in one transaction." fields={['salesOrderId','warehouseId','productId','quantity']} onSave={v=>submit(`/api/sales-orders/${v.salesOrderId}/ship`,{warehouseId:v.warehouseId,productId:v.productId,quantity:Number(v.quantity)})}/>} 
 {tab==='reports'&&<section><h1>Reports</h1><p>Review low-stock items, immutable ledger history, or download a stable CSV snapshot.</p><div className="cards"><a href="/api/export/stock.csv">Export stock CSV</a><button onClick={async()=>{const x=await api('/api/reports/low-stock');setProducts(x.data)}}>Load low stock</button><button onClick={async()=>{const x=await api('/api/stock/ledger');setProducts(x.data)}}>Load ledger</button></div><Data rows={products}/></section>}</main></>}
function Data<T extends object>({rows}:{rows:T[]}){if(!rows.length)return <p className="empty">No records match this view.</p>;const keys=Object.keys(rows[0]!).slice(0,7);return <div className="table"><table><thead><tr>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const record=r as Record<string,unknown>;return <tr key={String(record.id??i)}>{keys.map(k=><td key={k}>{String(record[k]??'')}</td>)}</tr>})}</tbody></table></div>}
function QuickProduct({onSave}:{onSave:(x:unknown)=>void}){return <form className="panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({sku:f.get('sku'),name:f.get('name'),unit:'each',reorderThreshold:Number(f.get('threshold'))})}}><h2>Add product</h2><label>SKU<input name="sku" required/></label><label>Name<input name="name" required/></label><label>Reorder threshold<input name="threshold" type="number" min="0" defaultValue="0" required/></label><button>Add product</button></form>}
function Adjust({rows,onSave}:{rows:Stock[];onSave:(x:unknown)=>void}){return <form className="panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({productId:f.get('product'),warehouseId:f.get('warehouse'),quantity:+String(f.get('quantity')),reason:f.get('reason')})}}><h2>Inventory adjustment</h2><label>Item<select name="product">{rows.map(x=><option key={x.product_id+x.warehouse_id} value={x.product_id}>{x.sku} — {x.warehouse_code}</option>)}</select></label><label>Warehouse ID<input name="warehouse" defaultValue={rows[0]?.warehouse_id} required/></label><label>Quantity delta<input name="quantity" type="number" required/></label><label>Reason<input name="reason" minLength={3} required/></label><button>Record adjustment</button></form>}
function Workflow({title,help,fields,onSave}:{title:string;help:string;fields:string[];onSave:(v:Record<string,string>)=>void}){return <section><h1>{title}</h1><p>{help}</p><form className="panel" onSubmit={e=>{e.preventDefault();onSave(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>)}}>{fields.map(f=><label key={f}>{f.replace(/([A-Z])/g,' $1')}<input name={f} type={f.includes('quantity')||f.includes('Cents')?'number':'text'} min={f.includes('quantity')?'1':undefined} required/></label>)}<button>Submit</button></form></section>}
