import fs from 'node:fs'; import path from 'node:path'; import express, { type NextFunction, type Request, type Response } from 'express'; import cors from 'cors'; import type { Db } from './db.js'; import { uid } from './db.js';
import { can, DomainError, type Permission, type Role } from '../../../packages/domain/src/index.js'; import { pageQuery, productInput, warehouseInput, supplierInput, purchaseInput, salesInput, quantityCommand, adjustmentInput, transferInput, returnInput } from '../../../packages/contracts/src/index.js'; import { adjust, cancelSale, createAndReserveSale, createPurchase, processReturn, receive, ship, submitPurchase, transfer } from './inventory.js';
// Express's declaration-merging API requires a namespace declaration.
// eslint-disable-next-line @typescript-eslint/no-namespace
declare global { namespace Express { interface Request { actor?:{userId:string;orgId:string;role:Role}; correlationId?:string } } }
const parse=<T>(schema:{parse:(x:unknown)=>T},value:unknown)=>schema.parse(value);
export function createApp(db:Db){const app=express(),webRoot=path.resolve('dist/apps/web');app.disable('x-powered-by');app.use(cors());if(fs.existsSync(webRoot))app.use(express.static(webRoot));app.use(express.json({limit:'1mb'}));app.use((req,res,next)=>{req.correlationId=String(req.header('x-correlation-id')??uid('req'));res.setHeader('x-correlation-id',req.correlationId);next();});
  app.get('/health/live',(_q,r)=>r.json({status:'ok'})); app.get('/health/ready',(_q,r)=>{try{db.prepare('SELECT 1').get();r.json({status:'ready'});}catch{r.status(503).json({status:'not_ready'});}});
  app.post('/api/login',(req,res)=>{const body=req.body as {email?:unknown;password?:unknown};const row=db.prepare('SELECT u.id,u.email,m.org_id,m.role FROM users u JOIN memberships m ON m.user_id=u.id WHERE u.email=? AND u.password=?').get(body.email,body.password) as {id:string;email:string;org_id:string;role:Role}|undefined;if(!row)return res.status(401).json({error:{code:'UNAUTHENTICATED',message:'Invalid credentials',correlationId:req.correlationId}});res.json({token:Buffer.from(`${row.id}:${row.org_id}`).toString('base64url'),user:{id:row.id,email:row.email,orgId:row.org_id,role:row.role}});});
  app.use('/api',(req,res,next)=>{const raw=req.header('authorization')?.replace(/^Bearer /,'');if(!raw)return res.status(401).json({error:{code:'UNAUTHENTICATED',message:'Authentication required',correlationId:req.correlationId}});try{const [userId,orgId]=Buffer.from(raw,'base64url').toString().split(':');const m=db.prepare('SELECT role FROM memberships WHERE user_id=? AND org_id=?').get(userId,orgId) as {role:Role}|undefined;if(!m)throw new Error();req.actor={userId:userId!,orgId:orgId!,role:m.role};next();}catch{return res.status(401).json({error:{code:'UNAUTHENTICATED',message:'Invalid session',correlationId:req.correlationId}});}});
  const permit=(p:Permission)=>(req:Request,res:Response,next:NextFunction)=>{if(!req.actor||!can(req.actor.role,p))return res.status(403).json({error:{code:'FORBIDDEN',message:'Operation not permitted',correlationId:req.correlationId}});next();};
  app.get('/api/products',(req,res)=>{const q=parse(pageQuery,req.query);const sort={name:'p.name',sku:'p.sku',created_at:'p.created_at',available:'available'}[q.sort];const rows=db.prepare(`SELECT p.*,coalesce(sum(s.on_hand),0) on_hand,coalesce(sum(s.reserved),0) reserved,coalesce(sum(s.on_hand-s.reserved),0) available FROM products p LEFT JOIN stock_levels s ON s.product_id=p.id WHERE p.org_id=? AND (p.name LIKE ? OR p.sku LIKE ?) GROUP BY p.id ORDER BY ${sort} ${q.direction},p.id LIMIT ? OFFSET ?`).all(req.actor!.orgId,`%${q.q}%`,`%${q.q}%`,q.limit,q.offset);res.json({data:rows,page:{limit:q.limit,offset:q.offset}});});
  app.post('/api/products',permit('catalog:write'),(req,res)=>{const b=parse(productInput,req.body),id=uid('prod');db.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?)').run(id,req.actor!.orgId,b.sku,b.name,b.unit,'active',b.reorderThreshold,1,new Date().toISOString());res.status(201).json({id,...b});});
  app.get('/api/warehouses',(req,res)=>res.json({data:db.prepare('SELECT * FROM warehouses WHERE org_id=? ORDER BY code').all(req.actor!.orgId)}));
  app.post('/api/warehouses',permit('catalog:write'),(req,res)=>{const b=parse(warehouseInput,req.body),id=uid('wh');db.prepare('INSERT INTO warehouses VALUES(?,?,?,?,1)').run(id,req.actor!.orgId,b.code,b.name);res.status(201).json({id,...b});});
  app.get('/api/suppliers',(req,res)=>res.json({data:db.prepare('SELECT * FROM suppliers WHERE org_id=? ORDER BY name').all(req.actor!.orgId)}));
  app.post('/api/suppliers',permit('catalog:write'),(req,res)=>{const b=parse(supplierInput,req.body),id=uid('sup');db.prepare('INSERT INTO suppliers VALUES(?,?,?,?,?,1)').run(id,req.actor!.orgId,b.name,b.email,b.leadDays);res.status(201).json({id,...b});});
  app.get('/api/stock',(req,res)=>res.json({data:db.prepare('SELECT s.*,p.sku,p.name,w.code warehouse_code,s.on_hand-s.reserved available FROM stock_levels s JOIN products p ON p.id=s.product_id JOIN warehouses w ON w.id=s.warehouse_id WHERE s.org_id=? ORDER BY p.name,w.code').all(req.actor!.orgId)}));
  app.post('/api/stock/adjust',permit('inventory:adjust'),(req,res)=>res.json(adjust(db,req.actor!,parse(adjustmentInput,req.body),requiredKey(req))));
  app.get('/api/stock/ledger',(req,res)=>{const rows=db.prepare('SELECT m.*,sum(quantity_delta) OVER(PARTITION BY product_id,warehouse_id ORDER BY created_at,id) running_balance FROM stock_movements m WHERE org_id=? ORDER BY created_at DESC,id DESC LIMIT 200').all(req.actor!.orgId);res.json({data:rows});});
  app.post('/api/purchase-orders',permit('purchase:write'),(req,res)=>{const b=parse(purchaseInput,req.body);const lines=b.lines.map(({productId,quantity,unitCostCents})=>unitCostCents===undefined?{productId,quantity}:{productId,quantity,unitCostCents});res.status(201).json(createPurchase(db,req.actor!,{supplierId:b.supplierId,warehouseId:b.warehouseId,lines}));});
  app.post('/api/purchase-orders/:id/submit',permit('purchase:write'),(req,res)=>res.json(submitPurchase(db,req.actor!,param(req,'id'))));
  app.post('/api/purchase-orders/:id/receive',permit('receive:write'),(req,res)=>res.json(receive(db,req.actor!,param(req,'id'),parse(quantityCommand,req.body),requiredKey(req))));
  app.post('/api/sales-orders',permit('sales:write'),(req,res)=>{const b=parse(salesInput,req.body);const lines=b.lines.map(({productId,quantity,unitPriceCents})=>unitPriceCents===undefined?{productId,quantity}:{productId,quantity,unitPriceCents});res.status(201).json(createAndReserveSale(db,req.actor!,{warehouseId:b.warehouseId,customerName:b.customerName,lines},requiredKey(req)));});
  app.post('/api/sales-orders/:id/ship',permit('ship:write'),(req,res)=>res.json(ship(db,req.actor!,param(req,'id'),parse(quantityCommand,req.body),requiredKey(req))));
  app.post('/api/sales-orders/:id/cancel',permit('sales:write'),(req,res)=>res.json(cancelSale(db,req.actor!,param(req,'id'))));
  app.post('/api/transfers',permit('inventory:adjust'),(req,res)=>res.status(201).json(transfer(db,req.actor!,parse(transferInput,req.body),requiredKey(req))));
  app.post('/api/returns',permit('ship:write'),(req,res)=>res.status(201).json(processReturn(db,req.actor!,parse(returnInput,req.body),requiredKey(req))));
  app.get('/api/reports/low-stock',permit('reports:read'),(req,res)=>res.json({data:db.prepare('SELECT p.sku,p.name,w.code,s.on_hand,s.reserved,s.on_hand-s.reserved available,p.reorder_threshold FROM stock_levels s JOIN products p ON p.id=s.product_id JOIN warehouses w ON w.id=s.warehouse_id WHERE s.org_id=? AND s.on_hand-s.reserved<=p.reorder_threshold ORDER BY available,p.sku').all(req.actor!.orgId)}));
  app.get('/api/export/stock.csv',permit('reports:read'),(req,res)=>{const rows=db.prepare('SELECT p.sku,p.name,w.code,s.on_hand,s.reserved,s.on_hand-s.reserved available FROM stock_levels s JOIN products p ON p.id=s.product_id JOIN warehouses w ON w.id=s.warehouse_id WHERE s.org_id=? ORDER BY p.sku,w.code').all(req.actor!.orgId) as Record<string,unknown>[];res.type('text/csv').set('content-disposition','attachment; filename=stock.csv').send(['sku,name,warehouse,on_hand,reserved,available',...rows.map(r=>[r.sku,r.name,r.code,r.on_hand,r.reserved,r.available].map(csv).join(','))].join('\n'));});
  app.post('/api/import/products.csv',permit('catalog:write'),express.text({type:'text/csv',limit:'256kb'}),(req,res)=>{const lines=String(req.body).replaceAll('\r','').split('\n').filter(Boolean);if(lines.shift()?.trim()!=='sku,name,unit,reorder_threshold')throw new DomainError('VALIDATION_ERROR','Expected header sku,name,unit,reorder_threshold',422);if(lines.length>1000)throw new DomainError('VALIDATION_ERROR','Import is limited to 1000 rows',422);const results=lines.map((raw,index)=>{try{const [sku,name,unit,threshold]=parseCsvLine(raw),b=parse(productInput,{sku,name,unit,reorderThreshold:Number(threshold)}),productId=uid('prod');db.prepare('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?)').run(productId,req.actor!.orgId,b.sku,b.name,b.unit,'active',b.reorderThreshold,1,new Date().toISOString());return{row:index+2,status:'accepted',id:productId};}catch(e){return{row:index+2,status:'rejected',message:e instanceof Error?e.message:'Invalid row'};}});res.status(207).json({data:results,summary:{accepted:results.filter(x=>x.status==='accepted').length,rejected:results.filter(x=>x.status==='rejected').length}});});
  app.get('/api/audit',permit('reports:read'),(req,res)=>res.json({data:db.prepare('SELECT * FROM audit_events WHERE org_id=? ORDER BY created_at DESC LIMIT 100').all(req.actor!.orgId)}));
  app.use((err:unknown,req:Request,res:Response,next:NextFunction)=>{void next;const z=err as {issues?:unknown;code?:string;message?:string;status?:number};const status=z.status??(z.issues?422:z.code?.startsWith('SQLITE_CONSTRAINT')?409:500);const code=z instanceof DomainError?z.code:z.issues?'VALIDATION_ERROR':status===409?'CONFLICT':'INTERNAL_ERROR';console.error(JSON.stringify({level:'error',event:'request.failed',correlationId:req.correlationId,code,status}));res.status(status).json({error:{code,message:status===500?'Unexpected server error':z.message??'Request failed',details:z.issues,correlationId:req.correlationId}});});return app;}
function requiredKey(req:Request){const k=req.header('idempotency-key');if(!k||k.length>100)throw new DomainError('IDEMPOTENCY_KEY_REQUIRED','Valid Idempotency-Key header required',400);return k;}
function param(req:Request,name:string){const value=req.params[name];if(typeof value!=='string')throw new DomainError('VALIDATION_ERROR',`Invalid ${name}`,400);return value;}
function csv(v:unknown){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
function parseCsvLine(line:string){const fields:string[]=[],pattern=/(?:^|,)("(?:[^"]|"")*"|[^,]*)/g;for(const match of line.matchAll(pattern)){const value=match[1]??'';fields.push(value.startsWith('"')?value.slice(1,-1).replaceAll('""','"'):value)}if(fields.length!==4)throw new Error('Expected four columns');return fields;}
