import express, { type NextFunction, type Request, type Response } from 'express';
import cors from 'cors';
import { randomUUID } from 'node:crypto';
import type { Db } from './db.js';
import { availabilityInput, commandInput, confirmInput, holdInput, roles, slotQuery, waitlistInput, rescheduleInput, lifecycleInput, type Role } from '../../../packages/contracts/src/index.js';
import { can, DomainError, type AppointmentState } from '../../../packages/domain/src/index.js';
import { confirmHold, createHold, discoverSlots, lifecycle, reschedule } from './scheduling.js';

// Express's declaration-merging API requires a namespace declaration.
// eslint-disable-next-line @typescript-eslint/no-namespace
declare global { namespace Express { interface Request { identity?: {id:string;orgId:string;role:Role}; correlationId?:string } } }
class HttpError extends Error { constructor(public status:number,public code:string,message:string){super(message);} }
const parse=(schema:{safeParse:(v:unknown)=>{success:boolean;data?:unknown;error?:{flatten:()=>unknown}}},value:unknown)=>{const result=schema.safeParse(value);if(!result.success)throw new HttpError(422,'VALIDATION_FAILED','Request validation failed');return result.data;};
export function createApp(db:Db){ const app=express(); app.disable('x-powered-by');app.use(cors({origin:false}));app.use(express.json({limit:'32kb'}));app.use((req,res,next)=>{req.correlationId=String(req.header('x-correlation-id')??randomUUID());res.setHeader('x-correlation-id',req.correlationId);next();});
  app.get('/health/live',(_req,res)=>res.json({status:'ok'})); app.get('/health/ready',(_req,res)=>{try{db.prepare('SELECT 1').get();res.json({status:'ready'});}catch{res.status(503).json({status:'not_ready'});}});
  app.use('/api',(req,_res,next)=>{const match=/^Bearer demo:([\w-]+):([\w-]+)$/.exec(req.header('authorization')??'');if(!match)return next(new HttpError(401,'UNAUTHENTICATED','Authentication required'));const row=db.prepare('SELECT id,organization_id as orgId,role FROM users WHERE id=?').get(match[1]) as {id:string;orgId:string;role:Role}|undefined;if(!row||row.role!==match[2]||!roles.includes(row.role))return next(new HttpError(401,'UNAUTHENTICATED','Invalid credentials'));req.identity=row;next();});
  const allow=(action:Parameters<typeof can>[1])=>(req:Request,_res:Response,next:NextFunction)=>req.identity&&can(req.identity.role,action)?next():next(new HttpError(404,'NOT_FOUND','Resource not found'));
  app.get('/api/catalog',(req,res)=>{const org=req.identity!.orgId;res.json({locations:db.prepare('SELECT id,name,zone FROM locations WHERE organization_id=?').all(org),services:db.prepare('SELECT id,name,duration_min,price_cents FROM services WHERE organization_id=?').all(org),staff:db.prepare('SELECT s.id,u.name FROM staff s JOIN users u ON u.id=s.user_id WHERE u.organization_id=? AND s.active=1').all(org),resources:db.prepare('SELECT id,name,kind,capacity,active FROM resources WHERE organization_id=?').all(org)});});
  app.post('/api/availability/rules',allow('configure'),(req,res)=>{const x=parse(availabilityInput,req.body) as {staffId:string;weekday:number;startLocal:string;endLocal:string;effectiveFrom:string;effectiveTo:string};if(x.startLocal>=x.endLocal)throw new HttpError(422,'VALIDATION_FAILED','End must be after start');if(!db.prepare('SELECT 1 FROM staff s JOIN users u ON u.id=s.user_id WHERE s.id=? AND u.organization_id=?').get(x.staffId,req.identity!.orgId))throw new HttpError(404,'NOT_FOUND','Staff not found');const id=`rule-${randomUUID()}`;db.prepare('INSERT INTO availability_rules VALUES (?,?,?,?,?,?,?,?)').run(id,req.identity!.orgId,x.staffId,x.weekday,x.startLocal,x.endLocal,x.effectiveFrom,x.effectiveTo);res.status(201).json({id,...x});});
  app.get('/api/slots',(req,res)=>{const q=parse(slotQuery,req.query) as {serviceId:string;locationId:string;from:string;to:string;zone:string;staffId?:string};res.json({generatedAt:new Date().toISOString(),zone:q.zone,durationUnit:'minutes',slots:discoverSlots(db,req.identity!.orgId,q)});});
  app.post('/api/holds',allow('book'),(req,res)=>{const x=parse(holdInput,req.body) as {slotToken:string;idempotencyKey:string;customerId:string};if(req.identity!.role==='customer'&&x.customerId!==req.identity!.id)throw new HttpError(404,'NOT_FOUND','Customer not found');res.status(201).json(createHold(db,req.identity!,x.slotToken,x.customerId,x.idempotencyKey));});
  app.post('/api/appointments/confirm',allow('book'),(req,res)=>{const x=parse(confirmInput,req.body) as {holdId:string;idempotencyKey:string};const hold=db.prepare('SELECT customer_id FROM holds WHERE id=? AND organization_id=?').get(x.holdId,req.identity!.orgId) as {customer_id:string}|undefined;if(!hold||(req.identity!.role==='customer'&&hold.customer_id!==req.identity!.id))throw new HttpError(404,'NOT_FOUND','Hold not found');res.status(201).json(confirmHold(db,req.identity!,x.holdId,x.idempotencyKey));});
  app.get('/api/appointments',(req,res)=>{const {role,id,orgId}=req.identity!;const limit=Math.min(Number(req.query.limit)||50,100);const offset=Math.max(Number(req.query.offset)||0,0);let sql=`SELECT a.*,s.name service_name,u.name customer_name FROM appointments a JOIN services s ON s.id=a.service_id JOIN users u ON u.id=a.customer_id WHERE a.organization_id=?`;const args:unknown[]=[orgId];if(role==='customer'){sql+=' AND a.customer_id=?';args.push(id);}if(role==='provider'){sql+=' AND a.staff_id IN (SELECT id FROM staff WHERE user_id=?)';args.push(id);}sql+=' ORDER BY start_utc,id LIMIT ? OFFSET ?';args.push(limit,offset);res.json({items:db.prepare(sql).all(...args),limit,offset});});
  app.post('/api/appointments/:id/state',allow('check_in'),(req,res)=>{const x=parse(lifecycleInput,req.body) as {expectedVersion:number;reason?:string;state:AppointmentState};const appointmentId=routeParam(req,'id');if(req.identity!.role==='reception'&&x.state!=='checked_in')throw new HttpError(404,'NOT_FOUND','Appointment not found');if(req.identity!.role==='provider'&&!db.prepare('SELECT 1 FROM appointments a JOIN staff s ON s.id=a.staff_id WHERE a.id=? AND a.organization_id=? AND s.user_id=?').get(appointmentId,req.identity!.orgId,req.identity!.id))throw new HttpError(404,'NOT_FOUND','Appointment not found');res.json(lifecycle(db,req.identity!,appointmentId,x.state,x.expectedVersion,x.reason));});
  app.post('/api/appointments/:id/cancel',(req,res)=>{const x=parse(commandInput,req.body) as {expectedVersion:number;reason?:string};const appointmentId=routeParam(req,'id');const a=db.prepare('SELECT customer_id FROM appointments WHERE id=? AND organization_id=?').get(appointmentId,req.identity!.orgId) as {customer_id:string}|undefined;if(!a||(req.identity!.role==='customer'&&a.customer_id!==req.identity!.id))throw new HttpError(404,'NOT_FOUND','Appointment not found');res.json(lifecycle(db,req.identity!,appointmentId,'cancelled',x.expectedVersion,x.reason));});
  app.post('/api/appointments/:id/reschedule',allow('book'),(req,res)=>{const x=parse(rescheduleInput,req.body) as {slotToken:string;expectedVersion:number;reason?:string};const appointmentId=routeParam(req,'id');const a=db.prepare('SELECT customer_id FROM appointments WHERE id=? AND organization_id=?').get(appointmentId,req.identity!.orgId) as {customer_id:string}|undefined;if(!a||(req.identity!.role==='customer'&&a.customer_id!==req.identity!.id))throw new HttpError(404,'NOT_FOUND','Appointment not found');res.json(reschedule(db,req.identity!,appointmentId,x.slotToken,x.expectedVersion,x.reason));});
  app.post('/api/waitlist',allow('book'),(req,res)=>{const x=parse(waitlistInput,req.body) as {serviceId:string;locationId:string;customerId:string;earliest:string;latest:string};if(req.identity!.role==='customer'&&x.customerId!==req.identity!.id)throw new HttpError(404,'NOT_FOUND','Customer not found');const valid=db.prepare("SELECT 1 FROM services s JOIN locations l ON l.organization_id=s.organization_id JOIN users u ON u.organization_id=s.organization_id WHERE s.id=? AND l.id=? AND u.id=? AND s.organization_id=? AND u.role='customer'").get(x.serviceId,x.locationId,x.customerId,req.identity!.orgId);if(!valid)throw new HttpError(404,'NOT_FOUND','Wait-list target not found');const id=`wait-${randomUUID()}`;db.prepare("INSERT INTO waitlist VALUES (?,?,?,?,?,?,?,'waiting',NULL)").run(id,req.identity!.orgId,x.serviceId,x.locationId,x.customerId,x.earliest,x.latest);res.status(201).json({id,state:'waiting'});});
  app.get('/api/calendar.ics',allow('view_schedule'),(req,res)=>{const rows=db.prepare("SELECT id,start_utc,end_utc FROM appointments WHERE organization_id=? AND state!='cancelled' ORDER BY start_utc").all(req.identity!.orgId) as {id:string;start_utc:string;end_utc:string}[];const stamp=(s:string)=>s.replace(/[-:]/g,'').replace('.000','');res.type('text/calendar').send(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Northstar//Schedule//EN',...rows.flatMap(a=>['BEGIN:VEVENT',`UID:${a.id}@northstar.local`,`DTSTART:${stamp(a.start_utc)}`,`DTEND:${stamp(a.end_utc)}`,'SUMMARY:Reserved appointment','END:VEVENT']),'END:VCALENDAR'].join('\r\n'));});
  app.get('/api/reports/utilization',allow('view_schedule'),(req,res)=>res.json(db.prepare(`SELECT staff_id,count(*) booked,sum((julianday(end_utc)-julianday(start_utc))*1440) booked_minutes FROM appointments WHERE organization_id=? AND state!='cancelled' GROUP BY staff_id`).all(req.identity!.orgId)));
  app.use((error:unknown,req:Request,res:Response,next:NextFunction)=>{void next;const correlationId=req.correlationId??randomUUID();let status=500,code='INTERNAL',message='Unexpected server error';if(error instanceof HttpError){({status,code,message}=error);}else if(error instanceof DomainError){code=error.code;message=error.message;status=code==='NOT_FOUND'?404:code.includes('CONFLICT')||code==='SLOT_TAKEN'?409:code==='HOLD_EXPIRED'?410:422;}console.error(JSON.stringify({level:'error',event:'request_failed',correlationId,code,path:req.path}));res.status(status).json({error:{code,message,correlationId}});}); return app;
}
function routeParam(req:Request,name:string){const value=req.params[name];if(typeof value!=='string')throw new HttpError(404,'NOT_FOUND','Resource not found');return value;}
