import { createHmac, randomUUID } from 'node:crypto';
import { DateTime } from 'luxon';
import type { Db } from './db.js';
import { DomainError, resolveLocal, transition, type AppointmentState } from '../../../packages/domain/src/index.js';

type Service = { id:string; duration_min:number; before_buffer_min:number; after_buffer_min:number; price_cents:number };
type SlotPayload = { orgId:string; serviceId:string; locationId:string; staffId:string; resourceId:string|null; startUtc:string; endUtc:string; allocationStartUtc:string; allocationEndUtc:string; zone:string };
export type Slot = SlotPayload & { token:string; localStart:string; offsetMinutes:number };
const secret = process.env.SLOT_SECRET ?? 'local-demo-secret-change-in-production';
function signature(value:string): string { return createHmac('sha256',secret).update(value).digest('base64url'); }
export function encodeSlot(slot: SlotPayload): string { const body=Buffer.from(JSON.stringify(slot)).toString('base64url'); return `${body}.${signature(body)}`; }
export function decodeSlot(token:string): SlotPayload { const [body,sig,...extra]=token.split('.'); if (!body || !sig || extra.length || signature(body)!==sig) throw new DomainError('INVALID_SLOT','Invalid slot token'); try { return JSON.parse(Buffer.from(body,'base64url').toString()) as SlotPayload; } catch { throw new DomainError('INVALID_SLOT','Invalid slot token'); } }
function conflicts(db:Db, slot:SlotPayload, excludeAppointment?:string): boolean {
  const args = {staff:slot.staffId, resource:slot.resourceId, start:slot.allocationStartUtc, end:slot.allocationEndUtc, excluded:excludeAppointment ?? ''};
  const appointment = db.prepare(`SELECT 1 FROM appointments WHERE id != @excluded AND state != 'cancelled' AND (staff_id=@staff OR (resource_id IS NOT NULL AND resource_id=@resource)) AND allocation_start_utc < @end AND @start < allocation_end_utc LIMIT 1`).get(args);
  const hold = db.prepare(`SELECT 1 FROM holds WHERE state='active' AND expires_at > @now AND (staff_id=@staff OR (resource_id IS NOT NULL AND resource_id=@resource)) AND allocation_start_utc < @end AND @start < allocation_end_utc LIMIT 1`).get({...args,now:new Date().toISOString()});
  return Boolean(appointment || hold);
}
export function discoverSlots(db:Db, orgId:string, input:{serviceId:string;locationId:string;from:string;to:string;zone:string;staffId?:string}, now=new Date()):Slot[] {
  const service=db.prepare('SELECT * FROM services WHERE id=? AND organization_id=?').get(input.serviceId,orgId) as Service|undefined; if(!service) throw new DomainError('NOT_FOUND','Service not found');
  const location=db.prepare('SELECT zone FROM locations WHERE id=? AND organization_id=?').get(input.locationId,orgId) as {zone:string}|undefined; if(!location) throw new DomainError('NOT_FOUND','Location not found');
  const rules=db.prepare(`SELECT ar.* FROM availability_rules ar JOIN staff s ON s.id=ar.staff_id JOIN staff_services ss ON ss.staff_id=s.id WHERE ar.organization_id=? AND s.location_id=? AND ss.service_id=? AND s.active=1 AND (? IS NULL OR s.id=?)`).all(orgId,input.locationId,input.serviceId,input.staffId??null,input.staffId??null) as {staff_id:string;weekday:number;start_local:string;end_local:string;effective_from:string;effective_to:string}[];
  const resource=(db.prepare("SELECT id FROM resources WHERE organization_id=? AND location_id=? AND kind='room' AND active=1 ORDER BY id LIMIT 1").get(orgId,input.locationId) as {id:string}|undefined)?.id ?? null;
  const result:Slot[]=[]; let date=DateTime.fromISO(input.from,{zone:location.zone}).startOf('day'); const last=DateTime.fromISO(input.to,{zone:location.zone}).startOf('day'); if(last.diff(date,'days').days>31) throw new DomainError('RANGE_TOO_LARGE','Slot search is limited to 31 days');
  while(date<=last){ for(const rule of rules.filter(r=>r.weekday===date.weekday && input.from<=date.toISODate()! && date.toISODate()!<=input.to && r.effective_from<=date.toISODate()! && date.toISODate()!<=r.effective_to)){
      let cursor=DateTime.fromISO(`${date.toISODate()}T${rule.start_local}`,{zone:location.zone}); const end=DateTime.fromISO(`${date.toISODate()}T${rule.end_local}`,{zone:location.zone});
      while(cursor.plus({minutes:service.duration_min})<=end){ const local=cursor.toFormat("yyyy-MM-dd'T'HH:mm"); try { const resolved=resolveLocal(local,location.zone,cursor.offset); const start=DateTime.fromISO(resolved.utc); const finish=start.plus({minutes:service.duration_min}); const payload:SlotPayload={orgId,serviceId:service.id,locationId:input.locationId,staffId:rule.staff_id,resourceId:resource,startUtc:start.toUTC().toISO()!,endUtc:finish.toUTC().toISO()!,allocationStartUtc:start.minus({minutes:service.before_buffer_min}).toUTC().toISO()!,allocationEndUtc:finish.plus({minutes:service.after_buffer_min}).toUTC().toISO()!,zone:input.zone}; if(start.toMillis()>now.getTime()&&!conflicts(db,payload)) result.push({...payload,token:encodeSlot(payload),localStart:start.setZone(input.zone).toISO()!,offsetMinutes:start.setZone(input.zone).offset}); } catch(e){ if(!(e instanceof DomainError)) throw e; } cursor=cursor.plus({minutes:service.duration_min+service.before_buffer_min+service.after_buffer_min}); }
    } date=date.plus({days:1}); }
  return result.slice(0,200);
}
export function createHold(db:Db, actor:{id:string;orgId:string}, token:string, customerId:string, key:string, now=new Date()):Record<string,unknown>{
  const slot=decodeSlot(token); if(slot.orgId!==actor.orgId) throw new DomainError('NOT_FOUND','Slot not found');
  const customer=db.prepare("SELECT 1 FROM users WHERE id=? AND organization_id=? AND role='customer'").get(customerId,actor.orgId);if(!customer)throw new DomainError('NOT_FOUND','Customer not found');
  return db.transaction(()=>{ const existing=db.prepare('SELECT * FROM holds WHERE organization_id=? AND idempotency_key=?').get(actor.orgId,key) as Record<string,unknown>|undefined; if(existing)return existing; if(conflicts(db,slot))throw new DomainError('SLOT_TAKEN','Slot was just taken'); const id=`hold-${randomUUID()}`; const expires=new Date(now.getTime()+5*60_000).toISOString(); db.prepare(`INSERT INTO holds(id,organization_id,customer_id,service_id,location_id,staff_id,resource_id,start_utc,end_utc,allocation_start_utc,allocation_end_utc,display_zone,expires_at,state,idempotency_key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'active',?)`).run(id,actor.orgId,customerId,slot.serviceId,slot.locationId,slot.staffId,slot.resourceId,slot.startUtc,slot.endUtc,slot.allocationStartUtc,slot.allocationEndUtc,slot.zone,expires,key); return db.prepare('SELECT * FROM holds WHERE id=?').get(id) as Record<string,unknown>; }).immediate();
}
export function confirmHold(db:Db,actor:{id:string;orgId:string},holdId:string,key:string,now=new Date()):Record<string,unknown>{
  return db.transaction(()=>{ const duplicate=db.prepare('SELECT * FROM appointments WHERE organization_id=? AND booking_key=?').get(actor.orgId,key) as Record<string,unknown>|undefined;if(duplicate)return duplicate; const h=db.prepare('SELECT * FROM holds WHERE id=? AND organization_id=?').get(holdId,actor.orgId) as Record<string,unknown>|undefined;if(!h)throw new DomainError('NOT_FOUND','Hold not found');if(h.state==='confirmed')return db.prepare('SELECT * FROM appointments WHERE organization_id=? AND customer_id=? AND service_id=? AND start_utc=?').get(actor.orgId,h.customer_id,h.service_id,h.start_utc) as Record<string,unknown>;if(h.state!=='active'||String(h.expires_at)<=now.toISOString())throw new DomainError('HOLD_EXPIRED','Hold expired'); const svc=db.prepare('SELECT price_cents FROM services WHERE id=?').get(h.service_id) as {price_cents:number}; const id=`appt-${randomUUID()}`; db.prepare(`INSERT INTO appointments(id,organization_id,customer_id,service_id,location_id,staff_id,resource_id,start_utc,end_utc,allocation_start_utc,allocation_end_utc,display_zone,state,version,price_cents,booking_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'confirmed',1,?,?,?)`).run(id,actor.orgId,h.customer_id,h.service_id,h.location_id,h.staff_id,h.resource_id,h.start_utc,h.end_utc,h.allocation_start_utc,h.allocation_end_utc,h.display_zone,svc.price_cents,key,now.toISOString());db.prepare("UPDATE holds SET state='confirmed' WHERE id=?").run(holdId);db.prepare('INSERT INTO appointment_history(appointment_id,actor_id,action,to_state,at,snapshot) VALUES (?,?,?,?,?,?)').run(id,actor.id,'book','confirmed',now.toISOString(),JSON.stringify(h));db.prepare(`INSERT OR IGNORE INTO reminders VALUES (?,?,?,'email','pending',0,?,NULL)`).run(`rem-${id}`,id,new Date(Date.parse(String(h.start_utc))-24*3600000).toISOString(),`${id}:24h:email`);return db.prepare('SELECT * FROM appointments WHERE id=?').get(id) as Record<string,unknown>; }).immediate();
}
export function lifecycle(db:Db,actor:{id:string;orgId:string},id:string,next:AppointmentState,expected:number,reason?:string):Record<string,unknown>{ return db.transaction(()=>{const a=db.prepare('SELECT * FROM appointments WHERE id=? AND organization_id=?').get(id,actor.orgId) as Record<string,unknown>|undefined;if(!a)throw new DomainError('NOT_FOUND','Appointment not found');if(a.version!==expected)throw new DomainError('VERSION_CONFLICT','Appointment changed; refresh and retry');transition(a.state as AppointmentState,next);db.prepare('UPDATE appointments SET state=?,version=version+1 WHERE id=?').run(next,id);db.prepare('INSERT INTO appointment_history(appointment_id,actor_id,action,from_state,to_state,reason,at,snapshot) VALUES (?,?,?,?,?,?,?,?)').run(id,actor.id,'transition',a.state,next,reason??null,new Date().toISOString(),JSON.stringify(a));return db.prepare('SELECT * FROM appointments WHERE id=?').get(id) as Record<string,unknown>;}).immediate(); }
export function reschedule(db:Db,actor:{id:string;orgId:string},id:string,token:string,expected:number,reason?:string):Record<string,unknown>{const slot=decodeSlot(token);return db.transaction(()=>{const old=db.prepare('SELECT * FROM appointments WHERE id=? AND organization_id=?').get(id,actor.orgId) as Record<string,unknown>|undefined;if(!old)throw new DomainError('NOT_FOUND','Appointment not found');if(old.version!==expected)throw new DomainError('VERSION_CONFLICT','Appointment changed; refresh and retry');if(slot.orgId!==actor.orgId||slot.serviceId!==old.service_id)throw new DomainError('INVALID_SLOT','Slot is not valid for this appointment');if(conflicts(db,slot,id))throw new DomainError('SLOT_TAKEN','Replacement slot is unavailable; original booking preserved');db.prepare(`UPDATE appointments SET location_id=?,staff_id=?,resource_id=?,start_utc=?,end_utc=?,allocation_start_utc=?,allocation_end_utc=?,display_zone=?,version=version+1 WHERE id=?`).run(slot.locationId,slot.staffId,slot.resourceId,slot.startUtc,slot.endUtc,slot.allocationStartUtc,slot.allocationEndUtc,slot.zone,id);db.prepare('INSERT INTO appointment_history(appointment_id,actor_id,action,reason,at,snapshot) VALUES (?,?,?,?,?,?)').run(id,actor.id,'reschedule',reason??null,new Date().toISOString(),JSON.stringify(old));return db.prepare('SELECT * FROM appointments WHERE id=?').get(id) as Record<string,unknown>;}).immediate();}
