// ─────────────────────────────────────────────────────────────────────────
//  01 · DbContext and entities                            ★☆☆ warm-up
//  concepts: DbSet · SaveChanges · generated keys
//  run: dotnet run 01-dbcontext-and-entities.cs
// ─────────────────────────────────────────────────────────────────────────
//
//  A DbContext is a unit of work plus a set of tables. Each `DbSet<T>` is a
//  table; each `T` is a row shape. EF Core figures out the schema from
//  conventions — a property called `Id` (or `<Type>Id`) becomes the primary
//  key, and an integer key is auto-generated by the database.
//
//  Nothing you do to a DbContext hits the database until `SaveChanges()`.
//  Until then you are editing an in-memory graph that EF is watching.
//
//      db.Products.Add(new Product { Name = "widget" });   // nothing yet
//      db.SaveChanges();                                   // one INSERT
//
//  These exercises run against a real SQLite database held in memory — real
//  SQL, real constraints, no mocks, and nothing left on your disk.
//
//  Implement the three helpers below.
//
//  hint: after SaveChanges, EF writes the generated key back onto the object
//        you added — you do not have to re-query for it
#:sdk Microsoft.NET.Sdk.Web
#:package Microsoft.EntityFrameworkCore.Sqlite@10.0.11
#:project ../../_lib/Check/Check.csproj

using Bootcamp;
using static Bootcamp.Check;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

// Insert the product and return it, with its database-generated Id filled in.
Product AddProduct(ShopDb db, string name, decimal price)
{
    throw new NotImplementedException();
}

// Insert several products in ONE round trip to the database.
void AddMany(ShopDb db, params Product[] products)
{
    throw new NotImplementedException();
}

// How many products are stored. Must ask the database, not a cached list.
int CountProducts(ShopDb db)
{
    throw new NotImplementedException();
}

// ──────────────────────────── tests ──────────────────────────────────────

Test("a saved product gets a generated id", () =>
{
    using var db = NewDb();
    var product = AddProduct(db, "widget", 9.99m);

    Ok(product.Id > 0, "the database should have assigned an id");
});

Test("ids are assigned in insertion order", () =>
{
    using var db = NewDb();
    var first = AddProduct(db, "a", 1m);
    var second = AddProduct(db, "b", 2m);

    Eq(second.Id, first.Id + 1);
});

Test("the product can be read back", () =>
{
    using var db = NewDb();
    var saved = AddProduct(db, "widget", 9.99m);

    var found = db.Products.Single(p => p.Id == saved.Id);
    Eq(found.Name, "widget");
    Eq(found.Price, 9.99m);
});

Test("decimals survive the round trip exactly", () =>
{
    using var db = NewDb();
    AddProduct(db, "precise", 19.95m);

    // A float column would come back 19.949999999999999.
    Eq(db.Products.Single().Price, 19.95m);
});

Test("nothing is stored before SaveChanges", () =>
{
    using var db = NewDb();
    db.Products.Add(new Product { Name = "unsaved", Price = 1m });

    // The change tracker knows about it; the database does not.
    Eq(db.Products.AsNoTracking().Count(), 0);
});

Test("AddMany stores every product", () =>
{
    using var db = NewDb();
    AddMany(db,
        new Product { Name = "a", Price = 1m },
        new Product { Name = "b", Price = 2m },
        new Product { Name = "c", Price = 3m });

    Eq(CountProducts(db), 3);
});

Test("CountProducts reflects the database", () =>
{
    using var db = NewDb();
    Eq(CountProducts(db), 0);

    AddProduct(db, "one", 1m);
    Eq(CountProducts(db), 1);
});

// ──────────────────────────── types ──────────────────────────────────────

// Each test gets its own private in-memory database. The connection is kept
// open by the context: SQLite discards an in-memory database the moment the
// last connection to it closes.
static ShopDb NewDb()
{
    var connection = new SqliteConnection("Data Source=:memory:");
    connection.Open();

    var options = new DbContextOptionsBuilder<ShopDb>().UseSqlite(connection).Options;
    var db = new ShopDb(options);
    db.Database.EnsureCreated();
    return db;
}

public class Product
{
    public int Id { get; set; }              // convention: primary key
    public string Name { get; set; } = "";
    public decimal Price { get; set; }
}

public class ShopDb(DbContextOptions<ShopDb> options) : DbContext(options)
{
    public DbSet<Product> Products => Set<Product>();
}
